use std::collections::BTreeMap;

use crate::model::{ModuleInfo, ProjectKind, ProjectModel, WikiLang};
use crate::safe_name;

/// Resolve a module name to its on-disk file base name (no extension), keeping it
/// unique and free of `/` or `\` so it can never escape `Modules/`.
fn file_of(name_map: &BTreeMap<String, String>, n: &str) -> String {
    name_map.get(n).cloned().unwrap_or_else(|| safe_name(n))
}

/// All human-facing prose for a wiki page, in one language.
struct Labels {
    /// Suffix appended to the project title on the Home page, e.g. ` — Wiki`.
    home_title: &'static str,
    /// Suffix appended to the project title on the Architecture page.
    arch_title: &'static str,
    /// Auto-generation banner; contains a `{}` placeholder for the project kind.
    auto_gen: &'static str,
    /// `Modules` / `模块`.
    modules: &'static str,
    /// `Files` / `文件`.
    files: &'static str,
    /// `Lines of code` / `代码行数`.
    loc: &'static str,
    /// `Architecture` / `架构`.
    architecture: &'static str,
    /// Link line pointing at the dependency graph page.
    arch_link: &'static str,
    /// `Dependency edges` / `依赖边`.
    dep_edges: &'static str,
    /// `Languages` / `语言`.
    languages: &'static str,
    /// Shown when no internal dependencies are detected.
    no_deps: &'static str,
    /// Welcome line on the README index.
    welcome: &'static str,
    /// `Home` / `首页` (used as the README link label).
    home: &'static str,
    /// `Summary` / `摘要`.
    summary: &'static str,
    /// `Files` heading on a module page.
    files_h: &'static str,
    /// `Depends on` / `依赖于`.
    depends_on: &'static str,
    /// `Path` / `路径`.
    path: &'static str,
    /// `Type` / `类型`.
    type_l: &'static str,
    /// Colon used after bold labels (`：` in Chinese, `:` in English).
    colon: &'static str,
    /// Placeholder shown when no summary is available.
    placeholder: &'static str,
    /// Trailing "and N more files" note; contains a `{}` placeholder.
    more_files: &'static str,
}

fn labels(lang: WikiLang) -> &'static Labels {
    match lang {
        WikiLang::Zh => &ZH,
        WikiLang::En => &EN,
    }
}

static ZH: Labels = Labels {
    home_title: " — 项目 Wiki",
    arch_title: " — 架构",
    auto_gen: "由 `rustcode-wiki` 自动生成。项目类型：{}。",
    modules: "模块",
    files: "文件",
    loc: "代码行数",
    architecture: "架构",
    arch_link: "依赖关系图见 [Architecture.md](Architecture.md)。",
    dep_edges: "依赖边",
    languages: "语言",
    no_deps: "_未检测到内部依赖。_",
    welcome: "欢迎来到自动生成的项目 wiki。\n\n",
    home: "首页",
    summary: "摘要",
    files_h: "文件",
    depends_on: "依赖于",
    path: "路径",
    type_l: "类型",
    colon: "：",
    placeholder: "_在此填写自然语言摘要（运行 `rustcode wiki --llm`，或让 agent 补充）。_",
    more_files: "_……还有 {} 个文件。_",
};

static EN: Labels = Labels {
    home_title: " — Wiki",
    arch_title: " — Architecture",
    auto_gen: "Auto-generated by `rustcode-wiki`. Project kind: {}.",
    modules: "Modules",
    files: "Files",
    loc: "Lines of code",
    architecture: "Architecture",
    arch_link: "See [Architecture.md](Architecture.md) for the dependency graph.",
    dep_edges: "Dependency edges",
    languages: "Languages",
    no_deps: "_No internal dependencies detected._",
    welcome: "Welcome to the auto-generated project wiki.\n\n",
    home: "Home",
    summary: "Summary",
    files_h: "Files",
    depends_on: "Depends on",
    path: "Path",
    type_l: "Type",
    colon: ":",
    placeholder: "_Add a natural-language summary (run `rustcode wiki --llm`, or ask the agent to fill this in.)_",
    more_files: "_...and {} more files._",
};

/// Render the `Home.md` index page.
pub fn render_home(
    title: &str,
    model: &ProjectModel,
    name_map: &BTreeMap<String, String>,
    lang: WikiLang,
) -> String {
    let l = labels(lang);
    let mut s = String::new();
    s.push_str(&format!("# {title}{}\n\n", l.home_title));
    let banner = l.auto_gen.replace("{}", kind_name(&model.kind));
    s.push_str(&format!("_{banner}_\n\n"));
    s.push_str(&format!(
        "**{}{}** {} · **{}{}** {} · **{}{}** {}\n\n",
        l.modules,
        l.colon,
        model.modules.len(),
        l.files,
        l.colon,
        model.file_count,
        l.loc,
        l.colon,
        model.loc
    ));
    s.push_str(&format!("## {}\n\n", l.modules));
    for m in &model.modules {
        s.push_str(&format!(
            "- [{}](Modules/{}.md) — {} ({} {})\n",
            m.name,
            file_of(name_map, &m.name),
            m.kind,
            m.loc,
            l.loc
        ));
    }
    s.push_str(&format!("\n## {}\n\n{}\n", l.architecture, l.arch_link));
    s.push_str(&format!("\n## {}\n\n", l.languages));
    for (lang_label, n) in &model.languages {
        s.push_str(&format!("- {}: {}\n", lang_label, n));
    }
    s
}

/// Render the `Architecture.md` page (Mermaid diagram + dependency edges).
pub fn render_architecture(
    title: &str,
    model: &ProjectModel,
    diagram: &str,
    name_map: &BTreeMap<String, String>,
    lang: WikiLang,
) -> String {
    let _ = name_map;
    let l = labels(lang);
    let mut s = String::new();
    s.push_str(&format!("# {title}{}\n\n", l.arch_title));
    s.push_str("```mermaid\n");
    s.push_str(diagram);
    s.push_str("```\n\n");
    s.push_str(&format!("## {}\n\n", l.dep_edges));
    let mut any = false;
    for m in &model.modules {
        for d in &m.depends_on {
            any = true;
            s.push_str(&format!("- `{}` → `{}`\n", m.name, d));
        }
    }
    if !any {
        s.push_str(l.no_deps);
        s.push('\n');
    }
    s.push_str(&format!("\n## {}\n\n", l.languages));
    for (lang_label, n) in &model.languages {
        s.push_str(&format!("- {}: {}\n", lang_label, n));
    }
    s
}

/// Render the top-level `README.md` index.
pub fn render_index(
    title: &str,
    model: &ProjectModel,
    name_map: &BTreeMap<String, String>,
    lang: WikiLang,
) -> String {
    let l = labels(lang);
    let mut s = String::new();
    s.push_str(&format!("# {title}\n\n"));
    s.push_str(l.welcome);
    s.push_str(&format!("- [{}](Home.md)\n", l.home));
    s.push_str(&format!("- [{}](Architecture.md)\n", l.architecture));
    s.push_str(&format!("- {}:\n", l.modules));
    for m in &model.modules {
        s.push_str(&format!(
            "  - [{}](Modules/{}.md)\n",
            m.name,
            file_of(name_map, &m.name)
        ));
    }
    s
}

/// Render one module page. When `summary` is `None`, a placeholder prompts the
/// reader (or an LLM enrichment pass) to fill in the natural-language description.
pub fn render_module(
    model: &ProjectModel,
    m: &ModuleInfo,
    summary: Option<&str>,
    name_map: &BTreeMap<String, String>,
    lang: WikiLang,
) -> String {
    let _ = model;
    let l = labels(lang);
    let mut s = String::new();
    s.push_str(&format!("# {}{}{}\n\n", l.modules, l.colon, m.name));
    let path_disp = if m.path.as_os_str().is_empty() {
        ".".to_string()
    } else {
        m.path.display().to_string()
    };
    s.push_str(&format!("- **{}{}** `{}`\n", l.path, l.colon, path_disp));
    s.push_str(&format!("- **{}{}** {}\n", l.type_l, l.colon, m.kind));
    s.push_str(&format!("- **{}{}** {}\n", l.loc, l.colon, m.loc));
    if !m.depends_on.is_empty() {
        s.push_str(&format!("- **{}{}** ", l.depends_on, l.colon));
        let links: Vec<String> = m
            .depends_on
            .iter()
            .map(|d| format!("[`{d}`]({}.md)", file_of(name_map, d)))
            .collect();
        s.push_str(&links.join(", "));
        s.push('\n');
    }
    s.push_str(&format!("\n## {}\n\n", l.summary));
    match summary {
        Some(text) => s.push_str(text),
        None => s.push_str(l.placeholder),
    }
    s.push('\n');
    s.push_str(&format!("\n## {}\n\n", l.files_h));
    let top: Vec<&crate::model::FileInfo> = if m.files.len() > 25 {
        m.files.iter().take(25).collect()
    } else {
        m.files.iter().collect()
    };
    for f in &top {
        s.push_str(&format!(
            "- `{}` ({} {}, {})\n",
            f.rel_path, f.loc, l.loc, f.lang
        ));
    }
    if m.files.len() > top.len() {
        let more = l
            .more_files
            .replace("{}", &(m.files.len() - top.len()).to_string());
        s.push_str(&format!("- {more}\n"));
    }
    s
}

/// Build the prompt used to ask an LLM for a natural-language summary of a module,
/// written in the requested `lang`.
pub fn module_enrich_prompt(model: &ProjectModel, m: &ModuleInfo, lang: WikiLang) -> String {
    let (role, proj, module, typ, path_l, loc_l, deps_l, key_files, instruction) = match lang {
        WikiLang::Zh => (
            "你正在为一个项目 wiki 撰写软件模块文档。\n\n",
            "项目",
            "模块",
            "类型",
            "路径",
            "代码行数",
            "依赖",
            "关键文件：\n",
            "请用 2-4 段简体中文撰写该模块的自然语言摘要，说明其职责、在系统中的位置以及值得注意的设计点。\
             使用纯 Markdown，不要加标题。只输出摘要文本。",
        ),
        WikiLang::En => (
            "You are documenting a software module for a project wiki.\n\n",
            "Project",
            "Module",
            "Type",
            "Path",
            "Lines of code",
            "Depends on",
            "Key files:\n",
            "Write a concise 2-4 paragraph natural-language summary of what this module does, \
             its responsibility in the larger system, and notable design points. Use plain \
             Markdown with no heading. Output only the summary text.",
        ),
    };
    let mut s = String::new();
    s.push_str(role);
    s.push_str(&format!(
        "{proj}: {}\n{module}: {}\n{typ}: {}\n{path_l}: {}\n{loc_l}: {}\n",
        model.name,
        m.name,
        m.kind,
        m.path.display(),
        m.loc
    ));
    if !m.depends_on.is_empty() {
        s.push_str(&format!("{deps_l}: {}\n", m.depends_on.join(", ")));
    }
    s.push('\n');
    s.push_str(key_files);
    for f in m.files.iter().take(15) {
        s.push_str(&format!("- {} ({} {})\n", f.rel_path, f.loc, loc_l));
    }
    s.push('\n');
    s.push_str(instruction);
    s
}

fn kind_name(k: &ProjectKind) -> &'static str {
    match k {
        ProjectKind::Rust => "Rust",
        ProjectKind::Node => "Node.js",
        ProjectKind::Python => "Python",
        ProjectKind::Go => "Go",
        ProjectKind::Mixed => "Multi-language",
        ProjectKind::Unknown => "Unknown",
    }
}
