use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use crate::diagram::render_mermaid;
use crate::docgen;
use crate::error::WikiError;
use crate::manifest::{hash_file, hash_tree, WikiManifest};
use crate::model::{ProjectModel, WikiLang};
use crate::safe_name;
use crate::scanner::{scan, ScanOptions};
use sha2::{Digest, Sha256};

/// Identifier written into `manifest.json` by this engine.
const WIKI_GENERATOR: &str = "rustcode-wiki";
/// Manifest schema version produced by this engine.
const WIKI_VERSION: u32 = 1;

/// State of the target wiki output directory before a run, used to decide whether
/// it is safe to write there.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WikiTargetState {
    /// No wiki present (or an empty directory); safe to generate.
    Missing,
    /// An auto-generated wiki from rustcode-wiki is present; updating is safe but
    /// normally requires confirmation.
    AutoGenerated,
    /// A directory exists that was NOT generated by rustcode-wiki; refuse to touch it.
    Foreign,
}

/// Options controlling a wiki generation / sync run.
pub struct WikiOptions {
    /// Project root to analyze.
    pub root: PathBuf,
    /// Optional output directory. Defaults to `<root>/.rustcode/wiki`.
    pub out_dir: Option<PathBuf>,
    /// Optional wiki title (defaults to the project name).
    pub title: Option<String>,
    /// Force a full regeneration even when nothing changed.
    pub force: bool,
    /// Maximum number of files to scan (safety cap).
    pub max_files: usize,
    /// Additional directory names to exclude from scanning.
    pub exclude_dirs: Vec<String>,
    /// Output languages. Empty means "both `zh` and `en`" (the default);
    /// otherwise only the listed languages are generated, each into its own
    /// `<out>/<lang>/` subtree.
    pub langs: Vec<WikiLang>,
    /// When the target wiki already exists and was auto-generated by us, skip the
    /// interactive confirmation prompt and update it. Foreign (non-generated)
    /// directories are always refused regardless of this flag.
    pub assume_yes: bool,
}

/// Resolve the effective language list: an explicit selection wins, otherwise the
/// default `zh` + `en` pair is used (Chinese primary, English secondary).
pub fn resolve_langs(opts: &WikiOptions) -> Vec<WikiLang> {
    if opts.langs.is_empty() {
        crate::model::DEFAULT_LANGS.to_vec()
    } else {
        opts.langs.clone()
    }
}

/// Outcome of a generation / sync run, used for user-facing summaries.
pub struct WikiResult {
    pub out_dir: PathBuf,
    pub modules: usize,
    pub created: Vec<PathBuf>,
    pub updated: Vec<PathBuf>,
    pub unchanged: usize,
    /// Files deleted during this run: generated pages whose module no longer
    /// exists, plus their orphaned LLM summary sidecars.
    pub removed: Vec<PathBuf>,
    /// Generated files whose on-disk content was manually edited by the user and
    /// therefore left untouched (preserved) during this run. Only populated when
    /// `force` is false; pass `force` to overwrite them.
    pub preserved: Vec<PathBuf>,
    pub diagram: String,
}

/// The wiki engine. Entry points: [`generate`](WikiEngine::generate) (always
/// writes) and [`sync`](WikiEngine::sync) (change-detected, no-op when stable).
pub struct WikiEngine;

impl WikiEngine {
    /// Always (re)write the wiki.
    pub fn generate(opts: &WikiOptions) -> Result<WikiResult, WikiError> {
        Self::run(opts, true)
    }

    /// Incremental: skip work when no source file or page changed.
    pub fn sync(opts: &WikiOptions) -> Result<WikiResult, WikiError> {
        Self::run(opts, false)
    }

    /// Pure structural analysis (no writing). Used by LLM enrichment passes.
    pub fn analyze(opts: &WikiOptions) -> Result<ProjectModel, WikiError> {
        scan(
            &opts.root,
            &ScanOptions {
                max_files: opts.max_files,
                exclude_dirs: opts.exclude_dirs.clone(),
            },
        )
    }

    /// Classify what (if anything) already exists at the target output directory,
    /// so callers can refuse to clobber user content that we did not create.
    pub fn precheck(opts: &WikiOptions) -> WikiTargetState {
        precheck_dir(&resolve_out_dir(&opts.root, opts.out_dir.as_deref()))
    }

    fn run(opts: &WikiOptions, force_generate: bool) -> Result<WikiResult, WikiError> {
        let out_dir = resolve_out_dir(&opts.root, opts.out_dir.as_deref());
        // Safety guard: never overwrite a directory the user created by hand.
        match precheck_dir(&out_dir) {
            WikiTargetState::Foreign => return Err(WikiError::foreign(&out_dir)),
            WikiTargetState::AutoGenerated if !opts.assume_yes => {
                return Err(WikiError::needs_confirmation(&out_dir))
            }
            _ => {}
        }
        std::fs::create_dir_all(&out_dir)?;

        let scan_opts = ScanOptions {
            max_files: opts.max_files,
            exclude_dirs: opts.exclude_dirs.clone(),
        };

        // Load the previous manifest early so we can cheaply decide whether a full
        // re-scan is even necessary (see the fast path below).
        let manifest_path = out_dir.join("manifest.json");
        let old = WikiManifest::load(&manifest_path);

        // Cheap change detection: stat every source file (no content read/parse).
        // When nothing has changed since the last run we skip the expensive full
        // `scan()` + render entirely. This keeps the TUI background auto-sync
        // (which polls `sync` on an interval) cheap on large repositories -- a
        // re-scan that would otherwise re-read and re-parse every source file on
        // every tick only happens when something actually changed.
        let new_stats = crate::scanner::scan_stats(&opts.root, &scan_opts);
        if !force_generate {
            if let Some(old_m) = &old {
                if !old_m.source_stats.is_empty()
                    && old_m.source_stats == new_stats
                    && old_m.wiki_files.iter().all(|f| out_dir.join(f).exists())
                    && old_m.wiki_file_hashes.iter().all(|(rel, h)| {
                        out_dir.join(rel).exists()
                            && hash_file(&out_dir.join(rel)).ok().as_deref() == Some(h.as_str())
                    })
                {
                    return Ok(WikiResult {
                        out_dir: out_dir.clone(),
                        modules: old_m.module_count,
                        created: Vec::new(),
                        updated: Vec::new(),
                        unchanged: old_m.wiki_files.len(),
                        removed: Vec::new(),
                        preserved: Vec::new(),
                        diagram: String::new(),
                    });
                }
            }
        }

        let model = scan(&opts.root, &scan_opts)?;
        let diagram = render_mermaid(&model);
        let title = opts.title.clone().unwrap_or_else(|| model.name.clone());
        let name_map = crate::module_file_names(&model);

        // Build the target file map: relative wiki path -> rendered content.
        // Each requested language gets its own subtree (`zh/`, `en/`, ...) so the
        // Chinese and English copies are kept as separate documents. LLM summaries
        // are persisted in `<lang>/Modules/<base>.summary.md` sidecar files so a
        // later `sync`/`generate` keeps the enriched text instead of overwriting it.
        let langs = resolve_langs(opts);
        let mut targets: BTreeMap<String, String> = BTreeMap::new();
        for &lang in &langs {
            let sub = lang.dir();
            targets.insert(
                format!("{sub}/Home.md"),
                docgen::render_home(&title, &model, &name_map, lang),
            );
            targets.insert(
                format!("{sub}/Architecture.md"),
                docgen::render_architecture(&title, &model, &diagram, &name_map, lang),
            );
            targets.insert(
                format!("{sub}/README.md"),
                docgen::render_index(&title, &model, &name_map, lang),
            );
            for m in &model.modules {
                let base = name_map
                    .get(&m.name)
                    .cloned()
                    .unwrap_or_else(|| safe_name(&m.name));
                let summary_path = out_dir
                    .join(sub)
                    .join("Modules")
                    .join(format!("{base}.summary.md"));
                let summary = if summary_path.exists() {
                    std::fs::read_to_string(&summary_path).ok()
                } else {
                    None
                };
                targets.insert(
                    format!("{sub}/Modules/{base}.md"),
                    docgen::render_module(&model, m, summary.as_deref(), &name_map, lang),
                );
            }
        }

        // Hash every source file that feeds a module page (change detection).
        let mut source_rel: Vec<String> = Vec::new();
        for m in &model.modules {
            for f in &m.files {
                source_rel.push(f.rel_path.clone());
            }
        }
        source_rel.sort();
        source_rel.dedup();
        let new_hashes = hash_tree(&opts.root, &source_rel);

        let mut result = WikiResult {
            out_dir: out_dir.clone(),
            modules: model.modules.len(),
            created: Vec::new(),
            updated: Vec::new(),
            unchanged: 0,
            removed: Vec::new(),
            preserved: Vec::new(),
            diagram,
        };

        // Fast path: nothing changed since last sync. "Nothing changed" also means
        // the user did not manually edit any generated file, so we verify the
        // content hashes we recorded last time still match the files on disk.
        if !force_generate {
            if let Some(old_m) = &old {
                let unchanged_source = old_m.source_hashes == new_hashes;
                let all_present = old_m.wiki_files.iter().all(|f| out_dir.join(f).exists());
                let files_intact = old_m.wiki_file_hashes.iter().all(|(rel, h)| {
                    out_dir.join(rel).exists()
                        && hash_file(&out_dir.join(rel)).ok().as_deref() == Some(h.as_str())
                });
                if unchanged_source
                    && all_present
                    && old_m.wiki_files.len() == targets.len()
                    && files_intact
                {
                    result.unchanged = targets.len();
                    return Ok(result);
                }
            }
        }

        let mut written: Vec<String> = Vec::new();
        let mut new_file_hashes: BTreeMap<String, String> = BTreeMap::new();
        for (rel, content) in &targets {
            let p = out_dir.join(rel);
            if let Some(parent) = p.parent() {
                std::fs::create_dir_all(parent)?;
            }
            let new_hash = hash_str(content);
            if p.exists() {
                let existing = std::fs::read_to_string(&p)?;
                if existing == *content {
                    // Identical to what we'd write: nothing to do.
                    result.unchanged += 1;
                    new_file_hashes.insert(rel.clone(), new_hash);
                    written.push(rel.clone());
                    continue;
                }
                // Content differs. Distinguish a legitimate regeneration (sources
                // changed, so our last-written copy differs from the new one) from a
                // user edit we must preserve.
                let user_edited = match &old {
                    Some(old_m) => old_m
                        .wiki_file_hashes
                        .get(rel)
                        .map(|h| h.as_str() != hash_str(&existing))
                        .unwrap_or(true),
                    None => true,
                };
                if user_edited && !opts.force {
                    // Preserve the user's manual edits: keep tracking the file but do
                    // not overwrite it. Record the *intended* hash so the next run
                    // still sees a conflict and keeps preserving it.
                    result.preserved.push(p.clone());
                    new_file_hashes.insert(rel.clone(), new_hash);
                    written.push(rel.clone());
                    continue;
                }
                std::fs::write(&p, content)?;
                result.updated.push(p.clone());
            } else {
                std::fs::write(&p, content)?;
                result.created.push(p.clone());
            }
            new_file_hashes.insert(rel.clone(), new_hash);
            written.push(rel.clone());
        }

        // Prune stale pages (e.g. a removed module).
        if let Some(old_m) = &old {
            for f in &old_m.wiki_files {
                if !targets.contains_key(f) {
                    let p = out_dir.join(f);
                    if p.exists() {
                        let _ = std::fs::remove_file(&p);
                        result.removed.push(p);
                    }
                    // Also prune the LLM enrichment sidecar of a removed module
                    // page. Sidecars (`<lang>/Modules/<base>.summary.md`) are
                    // written by the enrichment pass and are deliberately NOT in
                    // `targets`/`wiki_files`, so the loop above cannot see them;
                    // without this a deleted module would leave its summary
                    // behind and a same-named module reappearing later would
                    // wrongly reuse the stale text.
                    if let Some(sidecar_rel) = summary_sidecar_path(f) {
                        let sp = out_dir.join(&sidecar_rel);
                        if sp.exists() {
                            let _ = std::fs::remove_file(&sp);
                            result.removed.push(sp);
                        }
                    }
                }
            }
        }

        let new_manifest = WikiManifest {
            version: WIKI_VERSION,
            generated_at: now_string(),
            generator: WIKI_GENERATOR.to_string(),
            source_hashes: new_hashes,
            wiki_files: written,
            wiki_file_hashes: new_file_hashes,
            source_stats: new_stats,
            module_count: model.modules.len(),
        };
        new_manifest.save(&manifest_path)?;
        Ok(result)
    }
}

/// Classify the existing target directory. A parseable manifest carrying our
/// generator (or the legacy `version` we still emit) marks an auto-generated wiki;
/// anything else at that path is treated as foreign and left untouched.
fn precheck_dir(out_dir: &Path) -> WikiTargetState {
    let manifest = out_dir.join("manifest.json");
    if manifest.exists() {
        match WikiManifest::load(&manifest) {
            Some(m) if m.generator == WIKI_GENERATOR || m.version == WIKI_VERSION => {
                WikiTargetState::AutoGenerated
            }
            _ => WikiTargetState::Foreign,
        }
    } else if !out_dir.exists() {
        WikiTargetState::Missing
    } else {
        let non_empty = std::fs::read_dir(out_dir)
            .map(|mut d| d.next().is_some())
            .unwrap_or(false);
        if non_empty {
            WikiTargetState::Foreign
        } else {
            WikiTargetState::Missing
        }
    }
}

fn resolve_out_dir(root: &Path, override_dir: Option<&Path>) -> PathBuf {
    match override_dir {
        Some(d) if d.is_absolute() => d.to_path_buf(),
        Some(d) => root.join(d),
        None => root.join(".rustcode").join("wiki"),
    }
}

/// The LLM summary sidecar path corresponding to a generated module page, or
/// `None` when `rel` is not a module page.
///
/// `zh/Modules/foo.md` -> `Some("zh/Modules/foo.summary.md")`. Returns `None`
/// for anything else (non-module pages, non-`.md` files, and summary sidecars
/// themselves), so the prune loop never chases a sidecar of a sidecar. Rel
/// paths produced by this engine always use `/` separators, so string handling
/// is safe on every platform.
fn summary_sidecar_path(rel: &str) -> Option<String> {
    let (dir, file) = rel.rsplit_once('/')?;
    if dir != "Modules" && !dir.ends_with("/Modules") {
        return None;
    }
    let base = file.strip_suffix(".md")?;
    if base.ends_with(".summary") {
        return None;
    }
    Some(format!("{dir}/{base}.summary.md"))
}

fn now_string() -> String {
    match std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH) {
        Ok(d) => format!("{}", d.as_secs()),
        Err(_) => "0".to_string(),
    }
}

/// sha256 of an in-memory string, used to fingerprint generated file content so
/// we can tell a legitimate regeneration apart from a user edit.
fn hash_str(s: &str) -> String {
    let mut h = Sha256::new();
    h.update(s.as_bytes());
    format!("{:x}", h.finalize())
}
