/// Errors produced while scanning a project or rendering the wiki.
#[derive(Debug)]
pub enum WikiError {
    Io(std::io::Error),
    Toml(toml::de::Error),
    Json(serde_json::Error),
    NoProjectRoot,
    /// The target wiki directory exists but was not generated by rustcode-wiki;
    /// we refuse to overwrite foreign content.
    ForeignWiki(std::path::PathBuf),
    /// The target wiki directory holds an auto-generated wiki but the caller has
    /// not confirmed the update (set `WikiOptions::assume_yes` to proceed).
    NeedsConfirmation(std::path::PathBuf),
    Other(String),
}

impl std::fmt::Display for WikiError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            WikiError::Io(e) => write!(f, "io error: {e}"),
            WikiError::Toml(e) => write!(f, "toml parse error: {e}"),
            WikiError::Json(e) => write!(f, "json error: {e}"),
            WikiError::NoProjectRoot => write!(
                f,
                "could not locate a project root (no Cargo.toml / package.json / pyproject.toml / go.mod found)"
            ),
            WikiError::ForeignWiki(p) => write!(
                f,
                "refusing to overwrite {p:?}: it exists but was not generated by rustcode-wiki"
            ),
            WikiError::NeedsConfirmation(p) => write!(
                f,
                "wiki already exists at {p:?}; pass confirmation to update the auto-generated copy"
            ),
            WikiError::Other(s) => write!(f, "{s}"),
        }
    }
}

impl std::error::Error for WikiError {}

impl WikiError {
    /// Build a [`WikiError::ForeignWiki`] from a path.
    pub fn foreign(p: &std::path::Path) -> Self {
        WikiError::ForeignWiki(p.to_path_buf())
    }

    /// Build a [`WikiError::NeedsConfirmation`] from a path.
    pub fn needs_confirmation(p: &std::path::Path) -> Self {
        WikiError::NeedsConfirmation(p.to_path_buf())
    }
}

impl From<std::io::Error> for WikiError {
    fn from(e: std::io::Error) -> Self {
        WikiError::Io(e)
    }
}

impl From<toml::de::Error> for WikiError {
    fn from(e: toml::de::Error) -> Self {
        WikiError::Toml(e)
    }
}

impl From<serde_json::Error> for WikiError {
    fn from(e: serde_json::Error) -> Self {
        WikiError::Json(e)
    }
}
